### ISSUE TITLE
Using it in EasyAdmin

### ISSUE THREAD

**Issue by fernandosngular** [Arkounay/ux-collection#5]
I am trying use it in EasyAdmin, but:
- I havent yarn installed in my project.
- In configureCrud, it launch: "There are no registered paths for namespace "ArkounayUxCollection"."

**Comment by Arkounay** [comment]
Hi,

- If you haven't installed yarn it's not an issue but you need at least a js package manager like npm and webpack encore for bundle to work as it's using symfony ux. If you're willing to install everything, checkout how to install symfony ux https://symfony.com/doc/current/frontend/ux.html#installing-symfony-ux but that may be overkill for just collections :stuck_out_tongue: 
- If you have the error `"There are no registered paths for namespace "ArkounayUxCollection"` that probably means the bundle isn't installed, maybe because you had an error in composer when doing`composer require arkounay/ux-collection`. The error could be that you project's dependencies aren't compatible. If that's the case, you probably have the details through composer. Otherwise If you have a special setup maybe the bundle wasn't added in `config/bundle.php`

**Comment by fernandosngular** [comment]
Thank you very much, indeed the flex recipe was not executed and it did not have the bundle in bundles.php, now it works for me.

The only problem I keep having is that I can't load webpack / yarn.

Wouldn't it be easier to include a link to the required javascript file in the uxcollection branch itself?

Or at least that this was an option, because I have been installing things for several hours and it is quite complex to only include a javascript that I need.

Thanks again, great job

**Comment by aleksblendwerk** [comment]
I just tried it with EasyAdmin 4.x and the style sheets don't really match.

Besides that, the actual functionality seems nice.

**Comment by Arkounay** [comment]
> I just tried it with EasyAdmin 4.x and the style sheets don't really match.
> 
> Besides that, the actual functionality seems nice.


The style sheets should be ok for EasyAdmin 4 even if not perfect, unless it's a collection that has no `entry_type`

![image](https://user-images.githubusercontent.com/9340719/229066186-86623539-7661-4b55-99c7-35cc0823f73a.png)


We could always add a special css file designed for easyadmin to make it better, that would be toggled through the `controllers.json` file if needed
